### PR TITLE
Adds DOI and pub date to Item show

### PR DESCRIPTION
**Pull request by JPrevost**
This also removes abstract and changes the layout entirely.

closes #372 

(The modified form is a bug fix I noticed while working on this and is unrelated but seemed small enough to slide in with this work).

### CODE REVIEW

**Comment by JPrevost** [comment]
This is actually quite a departure for the display and thus probably deserves some discussion. As such, I've attached a screenshot:

screen shot 2015-10-05 at 12 50 11 pm

**Comment by JPrevost** [comment]
As you'll note in the screen shot, the following changes have been made:
- aesthetic changes to layout
- removed abstract
- removed number of Transfers
- added DOI
- added Published date

It is entirely possible to just add DOI and Pubdate without making these changes, but once I started looking at code I could stop myself from refactoring.

The main downside I see to this is that it no longer matches the styling on every other page on the site.

**Comment by richardrodgers** [comment]
As you'll recall, we never got a solid recommendation from the product owning side on what metadata to display on the item page. I'd say the main thing here is to see if Katherine or others prefer this (meaning, not just addition of requested fields, but removal of abstract, etc), or at least get a reaction of some sort.
Can it be put up on staging for others to see?

**Comment by JPrevost** [comment]
@richardrodgers Good point. I'll work with Katharine to confirm if my assumptions of what to remove are actually desired before moving ahead (and see if anything else should go in to avoid dragging this on for months).

**Comment by JPrevost** [comment]
@richardrodgers Katharine has signed off on this... any last thoughts before I merge?

**Comment by richardrodgers** [comment]
Nope - if customer is happy :+1:

**Pull request merged**
